[build]
  command = "yarn run build"
  publish = ".next"
  base = "."

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, deploy the lighthouse report to a path under your site
  # [plugins.inputs]
    # output_path = "reports/lighthouse.html"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NETLIFY_USE_YARN = "true"
